---
services:
  mysql:
    image: mysql
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3306:3306" 
    volumes:
      - mysql-data:/var/lib/mysql

  postgres:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgres/data

volumes:
  mysql-data:
  postgres-data:
